### ISSUE TITLE
The gip probably ignores transitive dependencies

### ISSUE THREAD

**Issue by terramexx** [czervenka/gap#6]
In new project created from gap I found a possible issue.

After adding new dependency to requirements.gip

<pre>-e git+https://github.com/czervenka/gapi.git#egg=gAPI</pre>

and processing import by calling

<pre>bin/gip install -r requirements.gip</pre>

My virtualenv is missing the PyCrypto dependency which is required by gAPI.

**Comment by czervenka** [comment]
Thanks for reporting.

I tried installing gApi with pip or directly "./setup.py".  Neithrer method install the required PyCrypto package.

I will fill bug in gApi.

**Comment by czervenka** [comment]
Should be fixed in gapi. Please try again
