### ISSUE TITLE
bin/gip install fails

### ISSUE THREAD

**Issue by krtek** [czervenka/gap#9]
Using bin/gip install fails while updating symlinks as it searches for `EGG-INFO` directory, while needed information is stored in `GaPy.egg-info`.

```
Updating symlinks ...
Traceback (most recent call last):
 File "./bin/gip", line 26, in <module>
   gip.run(join(dirname(dirname(__file__)), 'src', 'lib'))
 File "/home/tibor/.virtualenvs/csas/lib/python2.7/site-packages/gap/utils/gip.py", line 162, in run
   update_symlinks(lib_path)
 File "/home/tibor/.virtualenvs/csas/lib/python2.7/site-packages/gap/utils/gip.py", line 129, in update_symlinks
   for path in list_distribution_paths(dist):
 File "/home/tibor/.virtualenvs/csas/lib/python2.7/site-packages/gap/utils/gip.py", line 102, in list_distribution_paths
   for package in [ line.strip() for line in open(path).readlines() ]:
IOError: [Errno 2] No such file or directory: '/home/tibor/.virtualenvs/csas/src/gapi/EGG-INFO/top_level.txt'
```

**Comment by czervenka** [comment]
How did you installed gap in your virtualenv? I could not get gap installed in src :(

Could you please provide a step-by-step instructions how to reproduce the bug?

**Update:** gap installed with `pip install -e 'git+https://github.com/czervenka/gapi#egg=gapi` is in src directory. Anyway, I tried with latest version and everything still works as expected for me. Gip has found `~/venv/gap-test/src/gapi/gapi.egg-info/top_level.txt` correctly and use it instead for EGG-INF

**Comment by czervenka** [comment]
Also please what version are you using? `echo 'import gap; print gap.VERSION' | python`

**Comment by krtek** [comment]
It happens only on @tibor-kulcar's computer so we have to check it tomorrow. Maybe it's some discrepancy between Ubuntu and Mac OS?

**Comment by czervenka** [comment]
OK

**Comment by czervenka** [comment]
fixed :-)
